### ISSUE TITLE
Do you have any plans for this repository?

### ISSUE THREAD

**Issue by ghost** [spmn/steam-adblocker#4]
Hello, do you have any plans for this repository? If so, would you happen to know wether scriptlet injection would be possible in the steam browser?

Also, did you develop RakSAMP?

**Comment by spmn** [comment]
Hello, right now the repo is unmaintained. This summer I started porting the most important features of Brave adblocker to this project (scriptlet support included), but gave up after porting the new Rust adblock-rs engine. You can see the oxidize branch.

Technically it is possible to implement all features (network filters, cosmetic filters, scriptlets etc), but the main problem arrises from the fact that you must interact with the crude CEF API, written in C. You can't consume the CPP wrapper provided by libcef (or at least, I wasnt able to).

And regarding RakSAMP -- I did provide a few patches for it, but I was never an active developer there.

**Comment by ghost** [comment]
mersi de raspuns

**Comment by spmn** [comment]
... Aaaand he's gone
